name = "GSVD"
uuid = "58bd3cbf-f38f-4f28-838a-ee6437c2c51d"
authors = ["Ji Wang, Zhaojun Bai <jiiwang, zbai@ucdavis.edu>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
